import { Community } from "./types";

export const totalClearings = 12;
export const totalCommunityClearings = 4;
export const communities: Community[] = ["rabbit", "mouse", "fox"];
export const totalInhabitants = 2;
export const totalBuildings = 2;
export const totalProblems = 2;

export const nameTable = [
  "Patchwood",
  "Clutcher's Creek",
  "Rooston",
  "Limberly",
  "Flathome",
  "Opensky Haven",
  "Underleaf",
  "Pinehorn",
  "Milltown",
  "Allaburrow",
  "Tonnery",
  "Icetrap",
  "Ironvein",
  "Sundell",
  "Oakenhold",
  "Blackpaw's Dam",
  "Firehollow",
  "Windgap Refuge",
];

export const inhabitantTable = [
  "Mayor",
  "Farmer",
  "Armorer",
  "Rabble-Rouser",
  "Faction Recruiter",
  "Soldier",
  "Smith",
  "Thief",
  "Merchant",
  "Bandit",
  "Tailor/Cobbler",
  "Mason",
  "Guard Captain",
  "Local Regent",
  "Noble",
  "Mercenary",
  "Jeweler",
  "Assassin",
  "Rebel Leader",
  "Scholar",
  "Astronomer",
  "Baker",
  "Sheriff",
  "Gambler",
  "Enemy Captain",
  "Tax Collector",
  "Healer",
  "Tracker",
  "Barber",
  "Minstrel",
  "Village Elder",
  "Doctor",
  "Banker",
  "Historian",
  "Monk",
  "Judge",
];

export const buildingTable = [
  "Mill",
  "Guard tower",
  "Armory",
  "Orchard",
  "Almshouse",
  "Fountain",
  "Forge",
  "Fence/wall",
  "Infirmary",
  "Custom house",
  "Barracks",
  "Prison",
  "Well",
  "Longhouse",
  "Brewery",
  "Market",
  "Schoolhouse",
  "Graveyard",
  "Farm",
  "Archive",
  "Bakehouse",
  "Monastery",
  "Bridge",
  "Courthouse",
  "Kiln",
  "Larder",
  "Woodshop",
  "Tavern",
  "Dam",
  "Trading post",
  "Town Hall",
  "Grain silo",
  "Warehouse",
  "Inn",
  "Bank",
  "Aqueduct",
];

export const problemTable = [
  "Bear",
  "Tyranny",
  "Corruption",
  "Internal strife",
  "Road damage",
  "Fearmongering",
  "Natural disaster",
  "War",
  "Dissent/ rebellion",
  "Inflexible traditions",
  "Obsolescence",
  "Warmongering",
  "Bandits",
  "Money",
  "Lack of crucial resource",
  "Prejudice",
  "Cultural assimilation",
  "Smugglers",
  "Enemy occupation",
  "Inequality",
  "Lack of skilled labor",
  "Brutality",
  "Coup",
  "Thieves",
  "Famine",
  "Overpopulation",
  "Overtaxation",
  "Protection racket",
  "Poisoned supplies",
  "Censorship",
  "Sickness",
  "Lack of development",
  "Sabotage",
  "Xenophobia",
  "Dilapidated architecture",
  "Strange mystery",
];

export const defaultCorners: number[] = [0, 3, 8, 11];

export const defaultOppositeCorners: Record<number, number> = {
  0: 11,
  3: 8,
  8: 3,
  11: 0,
};

export const defaultPaths: Record<number, number[]> = {
  0: [1, 2, 3],
  1: [0, 4],
  2: [0, 5, 8],
  3: [0, 4, 5],
  4: [1, 3, 7],
  5: [2, 3, 6, 8, 10],
  6: [5, 7, 11],
  7: [4, 6, 11],
  8: [2, 5, 9],
  9: [8, 10],
  10: [5, 9, 11],
  11: [6, 7, 10],
};
